#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Sat Oct 10 13:32:28 ICT 2026
maven-metadata-apache.snapshots.xml.lastUpdated=1791567793702
maven-metadata-central-snapshots.xml.error=
maven-metadata-central-snapshots.xml.lastUpdated=1791613945191
maven-metadata-maven-default-http-blocker.xml.error=Could not transfer metadata org.apache.james\:james-server\:3.10.0-SNAPSHOT/maven-metadata.xml from/to maven-default-http-blocker (http\://0.0.0.0/)\: Blocked mirror for repositories\: [apache.snapshots (http\://repository.apache.org/snapshots, default, snapshots)]
maven-metadata-maven-default-http-blocker.xml/@default-maven-default-http-blocker-http\://0.0.0.0/.lastUpdated=1791613946855
maven-metadata-ossrh.xml.error=
maven-metadata-ossrh.xml.lastUpdated=1791613948388
maven-metadata-sonatype-nexus-snapshots.xml.error=
maven-metadata-sonatype-nexus-snapshots.xml.lastUpdated=1791613922589
