#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Sat Oct 10 00:44:43 ICT 2026
maven-metadata-apache.snapshots.xml.error=
maven-metadata-apache.snapshots.xml.lastUpdated=1791567883588
maven-metadata-central-portal-snapshots.xml.lastUpdated=1791567883589
