#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Sat Oct 10 13:32:29 ICT 2026
maven-metadata-apache.snapshots.xml.error=
maven-metadata-apache.snapshots.xml.lastUpdated=1791567882781
maven-metadata-central-portal-snapshots.xml.lastUpdated=1791567882782
maven-metadata-central-snapshots.xml.lastUpdated=1791613949858
maven-metadata-jvnet-nexus-snapshots.xml.error=Could not transfer metadata io.youtrackdb\:tinkerpop\:3.8.1-e3acec5-SNAPSHOT/maven-metadata.xml from/to jvnet-nexus-snapshots (https\://maven.java.net/content/repositories/snapshots)\: (certificate_unknown) PKIX path building failed\: sun.security.provider.certpath.SunCertPathBuilderException\: unable to find valid certification path to requested target
maven-metadata-jvnet-nexus-snapshots.xml/@default-jvnet-nexus-snapshots-https\://maven.java.net/content/repositories/snapshots/.lastUpdated=1791613949831
maven-metadata-maven-default-http-blocker.xml.error=Could not transfer metadata io.youtrackdb\:tinkerpop\:3.8.1-e3acec5-SNAPSHOT/maven-metadata.xml from/to maven-default-http-blocker (http\://0.0.0.0/)\: Blocked mirror for repositories\: [apache.snapshots (http\://repository.apache.org/snapshots, default, snapshots)]
maven-metadata-maven-default-http-blocker.xml/@default-maven-default-http-blocker-http\://0.0.0.0/.lastUpdated=1791613949847
maven-metadata-ossrh.xml.error=
maven-metadata-ossrh.xml.lastUpdated=1791613949866
maven-metadata-ow2-snapshot.xml.error=
maven-metadata-ow2-snapshot.xml.lastUpdated=1791613949842
maven-metadata-sonatype-nexus-snapshots.xml.error=
maven-metadata-sonatype-nexus-snapshots.xml.lastUpdated=1791613949833
