#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Sat Oct 10 13:32:16 ICT 2026
maven-metadata-apache.snapshots.xml.lastUpdated=1791567870215
maven-metadata-sonatype-nexus-snapshots.xml.error=
maven-metadata-sonatype-nexus-snapshots.xml.lastUpdated=1791613936335
